# Generated by Django 4.1 on 2023-04-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="photo/", verbose_name="image")),
                (
                    "add_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="registration date"
                    ),
                ),
                ("explanation", models.TextField(null=True)),
            ],
        ),
    ]
