# Generated by Django 4.1 on 2023-04-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="explanation",
            field=models.TextField(),
        ),
    ]
